version: '3.8'

services:
  gcc:
    build:
      context: docker/gcc
      dockerfile: Dockerfile
      args:
        QT_VERSION: 6.5.0
        QT_PATH: /opt/qt
        QT_HOST: linux
        QT_TARGET: desktop
        QT_ARCH: gcc_64
    image: sref/qt-docker:6.5-gcc
    tty: true
    volumes:
    - ./:/usr/src/app

  mingw:
    build:
      context: docker/mingw
      dockerfile: Dockerfile
      args:
        QT_VERSION: 6.5.0
        QT_PATH: C:\\Qt
        QT_HOST: windows
        QT_TARGET: desktop
        QT_ARCH: win64_mingw
    image: sref/qt-docker:6.5-mingw
    tty: true
    volumes:
    - ./:/usr/src/app
