version: '3.8'

services:
  gcc:
    build:
      context: docker/gcc
      dockerfile: Dockerfile
      args:
        QT_VERSION: 6.5.0
        QT_PATH: /opt/qt
        QT_MODULES:
        QT_HOST: linux
        QT_TARGET: desktop
        QT_ARCH: gcc_64
    image: roomsketcher/6.5-gcc:latest
    tty: true
    volumes:
    - ./:/usr/src/app

  mingw:
    build:
      context: docker/mingw
      dockerfile: Dockerfile
      args:
        QT_VERSION: 6.5.0
        QT_PATH: C:\\Qt
        QT_MODULES:
        QT_HOST: windows
        QT_TARGET: desktop
        QT_ARCH: win64_mingw
    image: roomsketcher/6.5-mingw:latest
    tty: true
    volumes:
    - ./:/usr/src/app
