name: Building(CMake)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docker/**'
    tags:
      - '*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docker/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linux-build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y catch2 libcurl4-openssl-dev libxcb-xinerama0 ninja-build ccache libxkbcommon-dev libxkbcommon-x11-dev doxygen graphviz

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ runner.os }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          install-deps: 'true'
          cache: 'true'
          tools: 'tools_ifw'
          aqtversion: '==3.1.*'
          py7zrversion: '==0.20.*'

      - name: Create Build Environment
        run: cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake -G Ninja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCPM_USE_LOCAL_PACKAGES=ON -DCPACK_IFW_ROOT=$IQTA_TOOLS/QtInstallerFramework/4.5/bin

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: cmake --build . --parallel $(nproc) --config $BUILD_TYPE

      - name: Test
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: ctest -C $BUILD_TYPE --output-on-failure --output-junit test-results.xml

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results-linux
          path: ${{ runner.workspace }}/build/test-results.xml

      - name: Package
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: cpack -C $BUILD_TYPE

      - name: Upload Artifact to Github
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: |
            ${{ runner.workspace }}/build/RoomSketcher-*-linux.tar.gz
            ${{ runner.workspace }}/build/RoomSketcher-*-linux.run
          retention-days: 2

      - name: Setup Pages
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: actions/configure-pages@v3

      - name: Build docs
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --target docs --parallel $(nproc) --config $BUILD_TYPE

      - name: Upload docs
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ runner.workspace }}/build/html

  windows-build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ runner.os }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          install-deps: 'true'
          cache: 'true'
          tools: 'tools_ifw tools_mingw90'
          aqtversion: '==3.1.*'
          py7zrversion: '==0.20.*'

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake -G Ninja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCPM_USE_LOCAL_PACKAGES=ON -DCPACK_IFW_ROOT=$IQTA_TOOLS/QtInstallerFramework/4.5/bin

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: cmake --build . --parallel $(nproc) --config $BUILD_TYPE

      - name: Test
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: ctest -C $BUILD_TYPE --output-on-failure --output-junit test-results.xml

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results-win
          path: ${{ runner.workspace }}/build/test-results.xml

      - name: Package
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cpack -C $BUILD_TYPE

      - name: Upload Artifact to Github
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
            ${{ runner.workspace }}/build/RoomSketcher-*-win64.tar.gz
            ${{ runner.workspace }}/build/RoomSketcher-*-win64.exe
          retention-days: 2

  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: [linux-build, windows-build]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Draft Release
        run: |
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes --draft

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload Windows Installer
        run: |
          gh release upload ${{ github.ref_name }} windows-build/RoomSketcher-${{ github.ref_name }}-win64.exe

      - name: Upload Windows Zip
        run: |
          gh release upload ${{ github.ref_name }} windows-build/RoomSketcher-${{ github.ref_name }}-win64.tar.gz

      - name: Upload Linux Installer
        run: |
          gh release upload ${{ github.ref_name }} linux-build/RoomSketcher-${{ github.ref_name }}-linux.run

      - name: Upload Linux Zip
        run: |
          gh release upload ${{ github.ref_name }} linux-build/RoomSketcher-${{ github.ref_name }}-linux.tar.gz

  docs-deploy:
    name: GitHub Docs Deploy
    runs-on: ubuntu-latest
    needs: linux-build
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2